name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~
            rm -rf vuna-calc
            git clone https://github.com/darlingxkill/vuna-calc-cicd-7678.git vuna-calc
            cd vuna-calc

            docker build -t vuna-calc .
            docker stop vuna-calc || true
            docker rm vuna-calc || true
            docker run -d -p 80:80 --name vuna-calc vuna-calc